import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "@/global/auth/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // TODO: implement dark mode toggle
  const isDarkMode = true;
  const colorScheme = isDarkMode ? "dark" : "";

  return (
    <html lang="en" className={`${colorScheme}`}>
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <AuthProvider>{children}</AuthProvider>
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"
          defer
        />
      </body>
    </html>
  );
}
